import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccessibilityProvider } from '../../lib/context/AccessibilityContext';
import AccessibilityWidget from '../../components/AccessibilityWidget';
import GoogleAuthProvider from '../../components/GoogleAuthProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleAuthProvider>
          <AccessibilityProvider>
            <a href="#main-content" className="skip-to-content" aria-label="Langsung ke Konten"></a>
            {children}
            <AccessibilityWidget />
          </AccessibilityProvider>
        </GoogleAuthProvider>
      </body>
    </html>
  );
}
